Fix for Python 3.7
C API breakage in 3.7 caused PyLibLo to fail to compile.
A more recent version (~3 years ago) works, but AFAICT that's because
they switched to Cython.

Compile error:
```
error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’
```